// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4WwKyWaWdIizr1nOr5Klr-zMF6rmvOEI',
    appId: '1:552522577022:web:c6f940372dd42b4808d42f',
    messagingSenderId: '552522577022',
    projectId: 'isinews-b23eb',
    authDomain: 'isinews-b23eb.firebaseapp.com',
    storageBucket: 'isinews-b23eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82ohZumEJjXiV1nP6PTJzcT-DIBUqGoU',
    appId: '1:552522577022:android:1c59ddc440e8070008d42f',
    messagingSenderId: '552522577022',
    projectId: 'isinews-b23eb',
    storageBucket: 'isinews-b23eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1Q5zcwrtt5vgDYw7pYEhC_K8LdPqqis',
    appId: '1:552522577022:ios:3dd1e2bac2f971e208d42f',
    messagingSenderId: '552522577022',
    projectId: 'isinews-b23eb',
    storageBucket: 'isinews-b23eb.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1Q5zcwrtt5vgDYw7pYEhC_K8LdPqqis',
    appId: '1:552522577022:ios:3dd1e2bac2f971e208d42f',
    messagingSenderId: '552522577022',
    projectId: 'isinews-b23eb',
    storageBucket: 'isinews-b23eb.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
